// Loader
export const LOADER_TRANSITION_DURATION = 4000
export const LOADER_DURATION_WITHOUT_IMAGES_TO_LOAD = 2000

// Page transition
export const DEFAULT_DELAY_BEFORE_LEAVE = 600
export const DEFAULT_DELAY_TO_START = 0